language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: mapgo-api
  api_key:
    secure: nnommZJcy1mjOUe1b5vMAZhWg5WxBYMoCCK0SWmyD4+xFGpX291IN+j71huqNiiMstvoWnpXIxDvsJCwRl85jahYd1Joouc+lvQ+S8ZNqsNuO+c058nbJD7Cqt2T6zPrAlFHQj2U+pkHirScEk9GXzRDqUr5/00nFYRn53a4b1Yy0ktb6k4K1UTtTDRwBNL253Y+PiHPqnS7E2xLWzJoz79xap2AuS0gkTjomS6zav1tf4N51yJtl8k7Ggh0iDU1WkfMbUbwMTZMgK0IaUs34O3wB1rDVrTo1oeCyy3Jbmnp31x4sWgKYNZjm0XVHsZccXz0iuQr7VgbITlq4cj0wNnmFR2+TL+1S9dX0ZNIsp5oeq5Yq8gW5pUijm08c+kWYJiDiXiKeTIZpaSpWGrWTgJfMj8B5wZzg7mLmrGHOGljP6Wk3uo3qf6vUrTdNBS+9oCBpk7Gz/79Guwm69z+k8LgvRLKcKZE+YqbV3ICkivFpOup337ujO1ARLxttPv0zzzjFjhxrBzq+oD4T8+7iGt04Ad8DBUn/oSMsu3/dfH6bmpEtJEVPI23zS2r7WhjhZ9uPq9lmmV6K/dT7rzrcPGL3Tp6fnbrG3cYmeetl/flEWN/jEvmJzE4vFveV7wYtx7JfMiIRqIE9Rg5lApRFhCQrgflNDJUDMAB4mT87Ac=
